# fonts
font_family JetBrainsMonoNL Nerd Font
font_size 14

# Shell integration is sourced and configured manually
shell_integration no-rc

# style
background_opacity 0.700000
enabled_layouts splits,stack

# keymaps
map ctrl+c copy_or_interrupt
map ctrl+shift+5 launch --location=vsplit --cwd=current
map ctrl+shift+enter launch --location=hsplit --cwd=current
map ctrl+shift+h resize_window narrower
map ctrl+shift+j resize_window shorter
map ctrl+shift+k resize_window taller
map ctrl+shift+l resize_window wider
map ctrl+shift+z toggle_layout stack
