# fonts
font_family JetBrainsMonoNL Nerd Font
font_size 14

# Shell integration is sourced and configured manually
shell_integration no-rc

# style
background_opacity 0.700000
enabled_layouts splits,stack

# keymaps
map ctrl+c copy_or_interrupt
map ctrl+shift+1 launch --location=hsplit --cwd=current
map ctrl+shift+2 launch --location=vsplit --cwd=current
map ctrl+shift+h resize_window narrower
map ctrl+shift+j resize_window shorter
map ctrl+shift+k resize_window taller
map ctrl+shift+l resize_window wider
map ctrl+shift+z toggle_layout stack

# sessions
map ctrl+shift+f5 combine | save_as_session --save-only --relocatable --use-foreground-process --match=session:. . | kitten notify "Kitty" "Session saved"
map ctrl+shift+f6 goto_session ~/.config/kitty/sessions
map ctrl+shift+f7 close_session

## make new windows/tabs belong to the current session if any
map kitty_mod+enter new_window_with_cwd
map kitty_mod+t new_tab_with_cwd
map kitty_mod+n new_os_window_with_cwd

# tabs
tab_title_template {session_name} {title}
